<#--
  Ubiquitous Language Glossary Template
  Generates a Markdown glossary from the domain model

  Available variables:
  - contextMap: The context map (if present)
  - boundedContexts: List of all bounded contexts
  - model: The full CML model
-->
# Ubiquitous Language Glossary

<#if model.name??>
**Model:** ${model.name}
</#if>

<#if contextMap?? && contextMap.state??>
**State:** ${contextMap.state}
</#if>

---

<#list boundedContexts as bc>
## ${bc.name}

<#if bc.domainVisionStatement??>
*${bc.domainVisionStatement}*

</#if>
<#if bc.responsibilities?? && bc.responsibilities?size gt 0>
**Responsibilities:**
<#list bc.responsibilities as resp>
- ${resp}
</#list>

</#if>
<#if bc.implementationTechnology??>
**Technology:** ${bc.implementationTechnology}

</#if>
<#if bc.aggregates?size gt 0>
### Aggregates

<#list bc.aggregates as agg>
#### ${agg.name}

<#if agg.aggregateRoot??>
| Term | Type | Description |
|------|------|-------------|
| **${agg.aggregateRoot.name}** | Aggregate Root | <#if agg.aggregateRoot.documentation??>${agg.aggregateRoot.documentation}<#else>Root entity of the ${agg.name} aggregate</#if> |
<#list agg.aggregateRoot.attributes as attr>
| ${attr.name} | ${attr.type} | <#if attr.key?? && attr.key>Key attribute<#else>-</#if> |
</#list>
</#if>

<#if agg.entities?size gt 0>
**Entities:**

| Term | Description |
|------|-------------|
<#list agg.entities as entity>
<#if !entity.aggregateRoot?? || !entity.aggregateRoot>
| **${entity.name}** | <#if entity.documentation??>${entity.documentation}<#else>Entity in ${agg.name}</#if> |
</#if>
</#list>
</#if>

<#if agg.valueObjects?size gt 0>
**Value Objects:**

| Term | Attributes | Description |
|------|------------|-------------|
<#list agg.valueObjects as vo>
| **${vo.name}** | <#list vo.attributes as attr>${attr.name}<#if attr?has_next>, </#if></#list> | <#if vo.documentation??>${vo.documentation}<#else>Value object in ${agg.name}</#if> |
</#list>
</#if>

<#if agg.domainEvents?size gt 0>
**Domain Events:**

| Event | Attributes | Description |
|-------|------------|-------------|
<#list agg.domainEvents as event>
| **${event.name}** | <#list event.attributes as attr>${attr.name}<#if attr?has_next>, </#if></#list> | <#if event.documentation??>${event.documentation}<#else>Domain event from ${agg.name}</#if> |
</#list>
</#if>

<#if agg.commands?size gt 0>
**Commands:**

| Command | Attributes | Description |
|---------|------------|-------------|
<#list agg.commands as cmd>
| **${cmd.name}** | <#list cmd.attributes as attr>${attr.name}<#if attr?has_next>, </#if></#list> | <#if cmd.documentation??>${cmd.documentation}<#else>Command for ${agg.name}</#if> |
</#list>
</#if>

<#if agg.services?size gt 0>
**Services:**

| Service | Operations |
|---------|------------|
<#list agg.services as svc>
| **${svc.name}** | <#list svc.operations as op>${op.name}()<#if op?has_next>, </#if></#list> |
</#list>
</#if>

</#list>
</#if>

---

</#list>

<#if contextMap?? && contextMap.relationships?size gt 0>
## Context Relationships

| Relationship | Type | Details |
|--------------|------|---------|
<#list contextMap.relationships as rel>
<#if rel.type == "Partnership">
| ${rel.participant1} <-> ${rel.participant2} | Partnership | Collaborative relationship |
<#elseif rel.type == "SharedKernel">
| ${rel.participant1} <-> ${rel.participant2} | Shared Kernel | Shared domain model |
<#elseif rel.type == "UpstreamDownstream">
| ${rel.upstream} -> ${rel.downstream} | Upstream/Downstream | <#if rel.upstreamPatterns?? && rel.upstreamPatterns?size gt 0>U: [<#list rel.upstreamPatterns as p>${p}<#if p?has_next>, </#if></#list>]</#if> <#if rel.downstreamPatterns?? && rel.downstreamPatterns?size gt 0>D: [<#list rel.downstreamPatterns as p>${p}<#if p?has_next>, </#if></#list>]</#if> |
</#if>
</#list>
</#if>

---

*Generated by Context Mapper MCP Server*
